num_steps: 3000
batch_size: 8
lr: 0.0003
memory_size: 300000
gamma: 0.90
multi_step: 1
target_entropy_ratio: 1.0
start_steps: 2000
update_interval: 4
target_update_interval: 99
use_per: False
num_eval_steps: 1000
max_episode_steps: 800
log_interval: 10
eval_interval: 1000
K: 10
